DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: mixup_pointnet2_run_1
  LOSS_NAME: smooth
  MODEL_NAME: pointnet2
  SEED: 1
  TASK: cls
TRAIN:
  l2: 0.0
AUG:
  NAME: mixup
  BETA: 1.
  PROB: 0.5
