DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: cutmix_k_rscnn_run_1
  LOSS_NAME: smooth
  MODEL_NAME: rscnn
  SEED: 1
  TASK: cls
TRAIN:
  l2: 0.0
AUG:
  NAME: cutmix_k
  BETA: 1.
  PROB: 0.5
