DATALOADER:
  batch_size: 18
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: cutmix_r_simpleview_run_1
  LOSS_NAME: smooth
  MODEL_NAME: simpleview
  SEED: 1
  TASK: cls
AUG:
  NAME: cutmix_r
  BETA: 1.
  PROB: 0.5