DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: pgd_dgcnn_run_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: dgcnn
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
AUG:
  NAME: pgd

