DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: dgcnn_pehist_run_1000
  LOSS_NAME: smooth
  MODEL_NAME: pehist
  SEED: 1
  TASK: cls
TRAIN:
  l2: 0.0
MODEL:
  PEHist:
    pool_param: 1000