DATALOADER:
  MODELNET40_DGCNN:
    train_data_path: ./data/modelnet40_ply_hdf5_2048/train_minus_valid_split_0.625_files.txt
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: dgcnn_dgcnn_0.5_run_1
  LOSS_NAME: smooth
  METRIC: acc
  MODEL_NAME: dgcnn
  SEED: 1
  TASK: cls
TRAIN:
  l2: 1e-4
