DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: dgcnn_pemedianlinear_run_1
  LOSS_NAME: smooth
  MODEL_NAME: pemedianlinear
  SEED: 1
  TASK: cls
TRAIN:
  l2: 0.0
