DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_pn2
  EXP_ID: pointnet2_pointnet_run_1
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet
  SEED: 1
  TASK: cls_trans
TRAIN:
  l2: 0.0
