DATALOADER:
  batch_size: 32
  num_workers: 0
EXP:
  DATASET: modelnet40_rscnn
  EXP_ID: rscnn_pointnet2_run_1
  LOSS_NAME: cross_entropy
  METRIC: acc
  MODEL_NAME: pointnet2
  SEED: 1
  TASK: cls
TRAIN:
  l2: 0.0
