name: "Deploy Documentation"

on: 
  push:
    tags:
      - "*"

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.7

    - name: Conda install dependecies
      shell: bash -l {0}
      run: conda install --yes -c conda-forge pythonocc-core=7.4.0 numpy scipy matplotlib vtk nose setuptools coveralls sphinx_rtd_theme sphinx python=3.7

    - name: Conda info
      shell: bash -l {0}
      run: conda info

    - name: Conda info
      shell: bash -l {0}
      run: cd docs && sphinx-build -b html -d build/doctrees  --keep-going --no-color -w '/tmp/sphinx-log' source build/html

    #- name: Create the new documentation
      #uses: ammaraskar/sphinx-action@master
      #with:
        #docs-folder: "docs/"
        #pre-build-command: "ls -l /usr/share"
        #build-command: "sphinx-build -b html -d build/doctrees  --keep-going --no-color -w '/tmp/sphinx-log' source build/html"


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        publish_dir: ./docs/build/html
        allow_empty_commit: true
